apiVersion: v1
kind: Secret
metadata:
  name: dacci-git-ssh
type: Opaque
stringData:
  id_ed25519: |
    REPLACE_WITH_OPENSSH_PRIVATE_KEY
  known_hosts: |
    github.com ssh-ed25519 REPLACE_WITH_GITHUB_HOST_KEY
